name: bokk_yonn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  http: ^0.13.5
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  intl: ^0.17.0

  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icones/
    - assets/onboarding/
    - assets/payment/
  uses-material-design: true

